@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Main\n<size:10>oop.classes" as oop.classes.Main [[Main.html]] {
        {static} +main(String[]): void
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
