@startuml
    namespace oop.classes {

        class TimeSheet [[TimeSheet.html]] {
            -employeeId: int
            -workingHours: int
            -sickLeave: int
            -vacation: int
            +TimeSheet(int)
            +TimeSheet(TimeSheet)
            +setWorkingHours(int): void
            +setSickLeave(int): void
            +setVacation(int): void
            +getEmployeeId(): int
            +getSickLeave(): int
            +getWorkingHours(): int
            +getVacation(): int
        }

        class TimeTrack [[TimeTrack.html]] {
            +TimeTrack(int)
            +TimeTrack(TimeSheet)
            +addWorkingHours(int): void
            +addSickLeave(int): void
            +addVacation(int): void
            +startNewPeriod(): void
        }

        class Main [[Main.html]] {
            {static} +main(String[]): void
        }

        TimeTrack --> TimeSheet: timeSheet\ncurrentTimeSheet
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
