@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>TimeTrack\n<size:10>oop.classes" as oop.classes.TimeTrack [[TimeTrack.html]] {
        -timeSheet: TimeSheet
        +TimeTrack(int)
        +TimeTrack(TimeSheet)
        +getCurrentTimeSheet(): TimeSheet
        +addWorkingHours(int): void
        +addSickLeave(int): void
        +addVacation(int): void
        +startNewPeriod(): void
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
